# ========================================
# Spring Boot - DEV profil (PostgreSQL)
# ========================================

# Server
server.port=8080

# ========================================
# PostgreSQL konfiguracija
# ========================================

#
#spring.datasource.url=jdbc:postgresql://localhost:5432/db_1
#spring.datasource.username=postgres
#spring.datasource.password=mario
#

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://ep-long-frog-a2mwsxyd-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_If9oAtTNUE5g

# Opcionalno - bolje performanse i pooling
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-test-query=SELECT 1

#debug
logging.level.org.springframework.security=DEBUG

#slike
spring.web.resources.static-locations=file:uploads/,classpath:/static/

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
