# ========================================
# Glavni / Default profil
# ========================================

# Aktiviraj dev profil (najva?nije!)
spring.profiles.active=dev

# Naziv aplikacije
spring.application.name=nekretnine


#Spring sexuuriityy toookeeen traje 24 sata
jwt.secret=mojTajniKljucKojiMoraBitiNajmanje32Karaktera!!
jwt.expiration=86400000 