# ========================================
# Glavni / Default profil
# ========================================

# Aktiviraj dev profil (najva?nije!)
spring.profiles.active=dev

# Naziv aplikacije
spring.application.name=nekretnine