# ========================================
# Glavni / Default profil
# ========================================

# Aktiviraj dev profil (najva?nije!)
spring.profiles.active=dev

# Naziv aplikacije
spring.application.name=nekretnine


#Spring sexuuriityy toookeeen traje 24 sata
jwt.secret=mojTajniKljucKojiMoraBitiNajmanje32Karaktera!!
jwt.expiration=86400000 

# Multipart (upload file-ova) settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=/var/uploads/nekretnine
app.upload.allowed-types=image/jpeg,image/png,image/webp